portal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing.as_view(),name='landing'),
    path('login/', views.Login.as_view(),name='Login'),
    path('logout/', views.Logout.as_view(),name='Logout'),
    path('student/', include('student.urls', namespace='student')),
    path('teacher/', include('teacher.urls', namespace='teacher')),

]

student/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('', views.StudentPage.as_view(),name = 'StudentPage'),
   
]

teacher/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.TeacherPage.as_view(),name = 'TeacherPage'),
    path('Admin/', views.AdminPage.as_view(),name = 'AdminPage'),
   path('scheduleLec/', views.scheduleLec.as_view(),name = 'scheduleLec'),
   path('markAttend/<str:topic>/', views.markAttend.as_view(),name = 'markAttend'),
    path('attendance/<topic>/', views.attendance.as_view(),name = 'attendance'),
     path('approve/<topic>/', views.approve.as_view(),name = 'approve'),
]

student/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.related import ForeignKey
from django.db.models import OneToOneField
# Create your models here.
class student(models.Model):
    user: OneToOneField = models.OneToOneField(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name

teacher/models.py
from typing import DefaultDict
from django.db import models
from django.db.models import OneToOneField
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE, DO_NOTHING


# Create your models here.
class teacher(models.Model):
    user: OneToOneField = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.first_name+" "+self.user.last_name   

class course(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=20)
    course_teacher = models.ForeignKey(teacher, on_delete=CASCADE)
    course_student = models.JSONField(default=list)
    def __str__(self):
        return self.name

class lecture(models.Model):
    topic = models.CharField(max_length=20)
    subject = models.ForeignKey(course, on_delete=CASCADE)
    date = models.DateTimeField()
    attendance = models.JSONField(default=list)
    lecturer = models.ForeignKey(teacher, on_delete=DO_NOTHING)
    approved = models.BooleanField(default=False)
    def __str__(self):
        return self.topic

portal/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, User

# Create your views here.
class landing(View):
    def get(self, request, template_name='landing.html'):
        return render(request, template_name)

class Login(View):
    def get(self, request, template_name='login.html'):
        return render(request,template_name)

    def post(self, request, template_name='login.html'):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        group = None
        if user is not None:
            if user.is_active:
                login(request, user)
                group = user.groups.all()[0].name
                if group == 'student_group':
                    return redirect('student:StudentPage')
                if group == 'teacher_group':
                    return redirect('teacher:TeacherPage')
                if group == 'admin_group':
                    return redirect('teacher:AdminPage')
                else:
                    return render(request, 'landing.html')
            else:
                return render(request, template_name, {'error_message': 'Your account has been disabled'})
        else:
            return render(request, template_name, {'error_message': 'Invalid Login'})



class Logout(View):
    def get(self, request,template_name="landing.html"):
        logout(request)
        return render(request, 'landing.html')
        

student/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, User

# Create your views here.
class StudentPage(View):
    def get(self,request,template_name='studentpage.html'):
        return render(request,template_name)

teacher/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, User
from .models import course, lecture, teacher

# Create your views here.
class AdminPage(View):
    def get(self,request,template_name='adminpage.html'):
        message={}
        lectures = lecture.objects.all()
        message['lectures']=lectures
        return render(request,template_name,message)

class TeacherPage(View):
    def get(self,request,template_name='teacherpage.html'):
        message={}
        thisteacher = teacher.objects.filter(user = request.user)
        thisteacher = thisteacher[0]
        lectures = lecture.objects.filter(lecturer = thisteacher)
        message['lectures']=lectures
        return render(request,template_name,message)

class scheduleLec(View):
    def get(self,request,template_name='schedule_lec.html'):
        return render(request,template_name)

    def post(self,request,template_name='schedule_lec.html'):
        message={}
        topic = request.POST.get('topic')
        subject = request.POST.get('subject')
        Subject = course.objects.all().filter(code = subject)
        attendance = ["0"]
        date = request.POST.get('date')
        lecturer = teacher.objects.filter(user = request.user)
        try:
            lectureData = lecture(topic=topic,subject=Subject[0],date=date,lecturer=lecturer[0],attendance=attendance)
            lectureData.save()
            message['error']="Lecture scheduled."
        except: 
            message['error']="Something went wrong!"
        return render(request,template_name,message)

class markAttend(View):
    def get(self,request,topic,template_name="mark_attendance.html"):
        message={}
        Lecture = lecture.objects.filter(topic=topic)
        message['lecture']= Lecture[0]
        Course = Lecture[0].subject
        students = Course.course_student
        message['students']= students
        return render(request,template_name,message)

    def post(self,request,topic,template_name="mark_attendance.html"):
        attendance = request.POST.getlist('list')
        lecture.objects.filter(topic=topic).update(attendance=attendance)
        Lecture = lecture.objects.filter(topic=topic)
        print(Lecture)
        print(attendance)
        message={}
        message['lecture']=Lecture
        return render(request,template_name,message)

class attendance(View):

    def get(self,request,topic,template_name="attendance.html"):
        message={}
        Lecture = lecture.objects.filter(topic=topic)
        message['lecture']= Lecture[0]
        Course = Lecture[0].subject
        students = Course.course_student
        message['students']= students
        return render(request,template_name,message)

class approve(View):

    def get(self,request,topic,template_name="approve.html"):
        message={}
        Lecture = lecture.objects.filter(topic=topic)
        message['lecture']= Lecture[0]
        Course = Lecture[0].subject
        students = Course.course_student
        message['students']= students
        return render(request,template_name,message)

    def post(self,request,topic,template_name="approve.html"):
        lecture.objects.filter(topic=topic).update(approved=True)
        return redirect('teacher:AdminPage')

portal/templates/adminpage.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
          {% if lectures %}
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Lectures</h4>
                  <p class="card-category"></p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Topic
                        </th>
                        <th>
                          Subject
                        </th>
                        <th>
                          Date
                        </th>
                        <th>
                          Attendance
                        </th>
                      </thead>
                      <tbody>
                        {% for i in lectures %}
                        <tr>
                        <td>{{i.topic}}
                        </td>
                        <td>{{i.subject}}
                        </td>
                        <td>{{i.date}}
                        </td>
                        <td>
                        {% if i.approved is True %}Approved
                        {% else %}
                        <a href="{% url 'teacher:approve' i.topic %}" class="btn btn-primary btn-sm">Give approval
                        </a>
                        {% endif %}
                        </tr>
                      {% endfor %}  
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            
          </div>
          {% endif %}
         
    
</div>

{% endblock %}

portal/templates/approve.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<button type="submit" class="btn btn-primary pull-right">Approve</button>
</form>
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">{{lecture.topic}}</h4>
                  <p class="card-category">{{lecture.subject}} {{lecture.date}}</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Student
                        </th>
                        <th>
                          Attendance
                        </th>
                      </thead>
                      <tbody>
                        {% for i in students %}
                        <tr>
                        <td>{{i}}
                        </td>
                        <td>
                        {% if i in lecture.attendance%}
                        Present
                        {% else %}
                        Absent
                        {% endif %}
                        </td>
                        </tr>
                      {% endfor %}  
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            
          </div>
          
    
</div>

{% endblock%}

portal/templates/attendance.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
<a href="{% url 'teacher:markAttend' lecture.topic %}" class="btn btn-primary btn-sm">Edit
                        </a>
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">{{lecture.topic}}</h4>
                  <p class="card-category">{{lecture.subject}} {{lecture.date}}</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Student
                        </th>
                        <th>
                          Attendance
                        </th>
                      </thead>
                      <tbody>
                        {% for i in students %}
                        <tr>
                        <td>{{i}}
                        </td>
                        <td>
                        {% if i in lecture.attendance%}
                        Present
                        {% else %}
                        Absent
                        {% endif %}
                        </td>
                        </tr>
                      {% endfor %}  
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            
          </div>
          
    
</div>

{% endblock%}

portal/templates/landing.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}


         
{% endblock%}

portal/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
          <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Login</h4>
                  <p>{{error_message}}</p>
                </div>
                <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                    <div class="row">
                        <div class="form-group">
                          <label class="bmd-label-floating">Username</label>
                          <input type="text" class="form-control" name="username">
                        </div>  
                    </div>
                    <div class="row">
                        <div class="form-group">
                          <label class="bmd-label-floating">Password</label>
                          <input type="password" class="form-control" name="password">
                        </div>  
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Login</button>
                    <div class="clearfix"></div>
                  </form>


                </div>
              </div>
            </div>
            
          </div>
        </div>

{% endblock%}

portal/templates/mark_attendance.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">{{lecture.topic}}</h4>
                  <p class="card-category">{{lecture.subject}} {{lecture.date}}</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Students
                        </th>
                        <th>
                          Mark Attendance
                        </th>
                      </thead>
                      <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                      <tbody>
                        {% for i in students %}
                        <tr>
                        <td>{{i}}
                        </td>
                        <td>
                        <div class="form-check">
    <label class="form-check-label">
        <input class="form-check-input" type="checkbox" name="list[]" value="{{ i.user.username}} checked">
        <span class="form-check-sign">
            <span class="check"></span>
        </span>
    </label>
</div>
                        </td>
                        </tr>
                      {% endfor %}  
                      </tbody>
                      <button type="submit" class="btn btn-primary pull-right">Save</button>
                      </form>

                      


                    </table>
                  </div>
                </div>
              </div>
            </div>
            
          </div>
          
         
    
</div>

{% endblock%}

portal/templates/schedule_lec.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
          <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Schedule Lecture</h4>
                  <p>{{error}}</p>
                </div>
                <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                    <div class="row">
                        <div class="form-group">
                          <label class="bmd-label-floating">Topic</label>
                          <input type="text" class="form-control" name="topic">
                        </div>  
                    </div>
                    <div class="row">
                        <div class="form-group">
                          <label class="bmd-label-floating">Course Code</label>
                          <input type="text" class="form-control" name="subject">
                        </div>  
                    </div>
                    <div class="row">
                        <div class="form-group">
                          <label class="bmd-label-floating">Date Time</label>
                          <input type="datetime-local" class="form-control" name="date">
                        </div>  
                    </div>
                    
                    <button type="submit" class="btn btn-primary pull-right">Confirm</button>
                    <div class="clearfix"></div>
                  </form>


                </div>
              </div>
            </div>
            
          </div>
        </div>

{% endblock%}

portal/templates/studentpage.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
          <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Student Login</h4>
                  <p>{{error_message}}</p>
                </div>
                <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                    <div class="row">
                        <div class="form-group">
                          <label class="bmd-label-floating">Username</label>
                          <input type="text" class="form-control" name="username">
                        </div>  
                    </div>
                    <div class="row">
                        <div class="form-group">
                          <label class="bmd-label-floating">Password</label>
                          <input type="password" class="form-control" name="password">
                        </div>  
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Login</button>
                    <div class="clearfix"></div>
                  </form>


                </div>
              </div>
            </div>
            
          </div>
        </div>

{% endblock%}

portal/templates/teacherpage.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Portal {% endblock%}
{% block content%}

<div class="container-fluid">
   <a href="{% url 'teacher:scheduleLec' %}" ><button class="btn btn-primary btn-sm">Schedule lecture</button></a>
          {% if lectures %}
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Lectures</h4>
                  <p class="card-category">Lectures conducted by you.</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Topic
                        </th>
                        <th>
                          Subject
                        </th>
                        <th>
                          Date
                        </th>
                        <th>
                          Attendance
                        </th>
                        <th>
                          View
                        </th>
                      </thead>
                      <tbody>
                        {% for i in lectures %}
                        <tr>
                        <td>{{i.topic}}
                        </td>
                        <td>{{i.subject}}
                        </td>
                        <td>{{i.date}}
                        </td>
                        <td><a href="{% url 'teacher:markAttend' i.topic %}" class="btn btn-primary btn-sm">Edit
                        </a>
                        </td>
                        <td><a href="{% url 'teacher:attendance' i.topic %}" class="btn btn-primary btn-sm">View
                        </a>
                        </td>
                        </tr>
                      {% endfor %}  
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            
          </div>
          {% endif %}
         
    
</div>

{% endblock %}